goods/api/urls.py
from rest_framework.routers import SimpleRouter

from goods.api import views

router = SimpleRouter()
router.register("catalog", views.CatalogViewSet)
router.register("trade_name", views.TradeNameViewSet)
router.register("maker", views.MakerViewSet)
router.register("packing", views.PackingViewSet)
router.register("unit", views.UnitViewSet)
router.register("original_packing", views.OriginalPackingViewSet)
router.register("dosage_packing", views.DosagePackingViewSet)
router.register("good", views.GoodViewSet)
router.register("good_image", views.GoodImageViewSet)


app_name = "goods-api"
urlpatterns = router.urls

goods/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from goods import views

app_name = "goods"

urlpatterns = [
    path("tradename/list/", views.TradeNameListView.as_view(), name="tradename-list"),
    path(
        "tradename/detail/<slug:slug>/",
        views.TradeNameDetailView.as_view(),
        name="tradename-detail",
    ),
    path(
        "tradename/create/",
        views.TradeNameCreateView.as_view(),
        name="tradename-create",
    ),
    path(
        "tradename/update/<slug:slug>/",
        views.TradeNameUpdateView.as_view(),
        name="tradename-update",
    ),
    path(
        "tradename/delete/<slug:slug>/",
        views.TradeNameDeleteView.as_view(),
        name="tradename-delete",
    ),
    path("maker/list/", views.MakerListView.as_view(), name="maker-list"),
    path(
        "maker/detail/<slug:slug>/",
        views.MakerDetailView.as_view(),
        name="maker-detail",
    ),
    path("maker/create/", views.MakerCreateView.as_view(), name="maker-create"),
    path(
        "maker/update/<slug:slug>/",
        views.MakerUpdateView.as_view(),
        name="maker-update",
    ),
    path(
        "maker/delete/<slug:slug>/",
        views.MakerDeleteView.as_view(),
        name="maker-delete",
    ),
    path("packing/list/", views.PackingListView.as_view(), name="packing-list"),
    path(
        "packing/detail/<slug:slug>/",
        views.PackingDetailView.as_view(),
        name="packing-detail",
    ),
    path("packing/create/", views.PackingCreateView.as_view(), name="packing-create"),
    path(
        "packing/update/<slug:slug>/",
        views.PackingUpdateView.as_view(),
        name="packing-update",
    ),
    path(
        "packing/delete/<slug:slug>/",
        views.PackingDeleteView.as_view(),
        name="packing-delete",
    ),
    path("unit/list/", views.UnitListView.as_view(), name="unit-list"),
    path(
        "unit/detail/<slug:slug>/", views.UnitDetailView.as_view(), name="unit-detail"
    ),
    path("unit/create/", views.UnitCreateView.as_view(), name="unit-create"),
    path(
        "unit/update/<slug:slug>/", views.UnitUpdateView.as_view(), name="unit-update"
    ),
    path(
        "unit/delete/<slug:slug>/", views.UnitDeleteView.as_view(), name="unit-delete"
    ),
    path("catalog/list/", views.CatalogListView.as_view(), name="catalog-list"),
    path(
        "catalog/detail/<slug:slug>/",
        views.CatalogDetailView.as_view(),
        name="catalog-detail",
    ),
    path("catalog/create/", views.CatalogCreateView.as_view(), name="catalog-create"),
    path(
        "catalog/update/<slug:slug>/",
        views.CatalogUpdateView.as_view(),
        name="catalog-update",
    ),
    path(
        "catalog/delete/<slug:slug>/",
        views.CatalogDeleteView.as_view(),
        name="catalog-delete",
    ),
    path(
        "originalpacking/list/",
        views.OriginalPackingListView.as_view(),
        name="originalpacking-list",
    ),
    path(
        "originalpacking/detail/<slug:slug>/",
        views.OriginalPackingDetailView.as_view(),
        name="originalpacking-detail",
    ),
    path(
        "originalpacking/create/",
        views.OriginalPackingCreateView.as_view(),
        name="originalpacking-create",
    ),
    path(
        "originalpacking/update/<slug:slug>/",
        views.OriginalPackingUpdateView.as_view(),
        name="originalpacking-update",
    ),
    path(
        "originalpacking/delete/<slug:slug>/",
        views.OriginalPackingDeleteView.as_view(),
        name="originalpacking-delete",
    ),
    path(
        "dosagepacking/list/",
        views.DosagePackingListView.as_view(),
        name="dosagepacking-list",
    ),
    path(
        "dosagepacking/detail/<slug:slug>/",
        views.DosagePackingDetailView.as_view(),
        name="dosagepacking-detail",
    ),
    path(
        "dosagepacking/create/",
        views.DosagePackingCreateView.as_view(),
        name="dosagepacking-create",
    ),
    path(
        "dosagepacking/update/<slug:slug>/",
        views.DosagePackingUpdateView.as_view(),
        name="dosagepacking-update",
    ),
    path(
        "dosagepacking/delete/<slug:slug>/",
        views.DosagePackingDeleteView.as_view(),
        name="dosagepacking-delete",
    ),
    path(
        "good/list/",
        views.GoodListView.as_view(),
        name="goods-list",
    ),
    path(
        "good/detail/<slug:slug>/",
        views.GoodDetailView.as_view(),
        name="goods-detail",
    ),
    path(
        "good/create/",
        views.GoodCreateView.as_view(),
        name="goods-create",
    ),
    path(
        "good/update/<slug:slug>/",
        views.GoodUpdateView.as_view(),
        name="goods-update",
    ),
    path(
        "good/delete/<slug:slug>/",
        views.GoodDeleteView.as_view(),
        name="goods-delete",
    ),
]

goods/models.py
# -*- coding: utf-8 -*-
import reversion
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from mptt.models import MPTTModel, TreeForeignKey
from slugify import slugify
from sorl.thumbnail import ImageField


@reversion.register()
class TradeName(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("Name"))
    slug = models.SlugField(max_length=250, editable=False, verbose_name=_("slug"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    class Meta:
        ordering = ["-name"]
        verbose_name = _("Trade name")
        verbose_name_plural = _("Trade names")

    def get_absolute_url(self):
        return reverse("goods:tradename-detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


@reversion.register()
class Maker(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("Name"))
    slug = models.SlugField(max_length=250, editable=False, verbose_name=_("slug"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    class Meta:
        ordering = ["-name"]
        verbose_name = _("Maker")
        verbose_name_plural = _("Makers")

    def get_absolute_url(self):
        return reverse("goods:maker-detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


@reversion.register()
class Packing(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("Name"))
    slug = models.SlugField(max_length=250, editable=False, verbose_name=_("slug"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    class Meta:
        ordering = ["-name"]
        verbose_name = _("Packing type")
        verbose_name_plural = _("Packing types")

    def get_absolute_url(self):
        return reverse("goods:packing-detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


@reversion.register()
class Unit(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name=_("Name"))
    slug = models.SlugField(max_length=250, editable=False, verbose_name=_("slug"))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    class Meta:
        ordering = ["-name"]
        verbose_name = _("Unit of measurement")
        verbose_name_plural = _("Units of measurement")

    def get_absolute_url(self):
        return reverse("goods:unit-detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


@reversion.register()
class OriginalPacking(models.Model):
    packing = models.ForeignKey(
        Packing, on_delete=models.PROTECT, verbose_name=_("Packing type")
    )
    quantity = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name=_("Quantity")
    )
    unit = models.ForeignKey(
        Unit, on_delete=models.PROTECT, verbose_name=_("Unit of measurement")
    )
    slug = models.SlugField(
        max_length=250, blank=True, editable=False, verbose_name=_("slug")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    def get_absolute_url(self):
        return reverse("goods:originalpacking-detail", args=[str(self.slug)])

    def __str__(self):
        return f"{self.packing} {self.quantity} {self.unit}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ("packing", "quantity", "unit")
        verbose_name = _("Original Packing")
        verbose_name_plural = _("Original Packings")


@reversion.register()
class DosagePacking(models.Model):
    packing = models.ForeignKey(
        Packing, on_delete=models.PROTECT, verbose_name=_("Packing type")
    )
    quantity = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name=_("Quantity")
    )
    unit = models.ForeignKey(
        Unit, on_delete=models.PROTECT, verbose_name=_("Unit of measurement")
    )
    slug = models.SlugField(
        max_length=250, blank=True, editable=False, verbose_name=_("slug")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    def get_absolute_url(self):
        return reverse("goods:dosagepacking-detail", args=[str(self.slug)])

    def __str__(self):
        return f"{self.packing} {self.quantity} {self.unit}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ("packing", "quantity", "unit")
        verbose_name = _("Dosage packing")
        verbose_name_plural = _("Dosage packings")


@reversion.register()
class Catalog(MPTTModel):
    name: models.CharField = models.CharField(max_length=250, verbose_name=_("Name"))
    parent = TreeForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name=_("children"),
    )
    slug: models.SlugField = models.SlugField(
        max_length=250, blank=True, editable=False, verbose_name=_("slug")
    )
    created: models.DateTimeField = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name=_("Created")
    )
    updated: models.DateTimeField = models.DateTimeField(
        auto_now=True, editable=False, verbose_name=_("Updated")
    )

    class Meta:
        verbose_name_plural = _("Catalogs")
        verbose_name = _("Catalog")

    def get_absolute_url(self):
        return reverse("goods:catalog-detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        super().save(*args, **kwargs)


@reversion.register()
class Good(models.Model):
    trade_name = models.ForeignKey(
        TradeName, on_delete=models.PROTECT, verbose_name=_("Trade name")
    )
    maker = models.ForeignKey(Maker, on_delete=models.PROTECT, verbose_name=_("Maker"))
    original_packing = models.ForeignKey(
        OriginalPacking, on_delete=models.PROTECT, verbose_name=_("Original packing")
    )
    dosage_packing = models.ForeignKey(
        DosagePacking,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Dosage packing"),
    )
    catalog = models.ForeignKey(
        Catalog, on_delete=models.PROTECT, verbose_name="Catalog"
    )
    slug = models.SlugField(
        max_length=250, blank=True, editable=False, verbose_name=_("slug")
    )
    full_name = models.CharField(
        max_length=300, blank=True, editable=False, verbose_name=_("Full name")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, verbose_name=_("Updated"))

    class Meta:
        unique_together = ("trade_name", "maker", "original_packing", "dosage_packing")
        verbose_name = _("Pharmaceutical good")
        verbose_name_plural = _("Pharmaceutical goods")

    def get_absolute_url(self):
        return reverse("goods:goods-detail", args=[str(self.slug)])

    def __str__(self):
        result = f"{self.maker.name}: {self.trade_name.name}"
        if self.dosage_packing is not None:
            result += f", {self.dosage_packing}"
        if self.original_packing is not None:
            result += f", {self.original_packing}"
        return result

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        self.full_name = self.__str__()
        super().save(*args, **kwargs)


@reversion.register()
class GoodImage(models.Model):
    image = ImageField(upload_to="thumbnails", verbose_name=_("Image"))
    good = models.ForeignKey(
        Good,
        on_delete=models.CASCADE,
        related_name="images",
        verbose_name=_("Parent"),
    )

    def __str__(self):
        return self.image.url

goods/forms.py
from django.forms import ModelForm

from goods import models


class TradeNameForm(ModelForm):
    class Meta:
        model = models.TradeName
        fields = ["name"]


class MakerForm(ModelForm):
    class Meta:
        model = models.Maker
        fields = ["name"]


class PackingForm(ModelForm):
    class Meta:
        model = models.Packing
        fields = ["name"]


class UnitForm(ModelForm):
    class Meta:
        model = models.Unit
        fields = ["name"]


class CatalogForm(ModelForm):
    class Meta:
        model = models.Catalog
        fields = ["name", "parent"]


class OriginalPackingForm(ModelForm):
    class Meta:
        model = models.OriginalPacking
        fields = ["packing", "quantity", "unit"]


class DosagePackingForm(ModelForm):
    class Meta:
        model = models.DosagePacking
        fields = ["packing", "quantity", "unit"]


class GoodForm(ModelForm):
    class Meta:
        model = models.Good
        fields = [
            "catalog",
            "trade_name",
            "maker",
            "original_packing",
            "dosage_packing",
        ]

goods/api/views.py
from rest_framework.permissions import DjangoObjectPermissions
from rest_framework.viewsets import ModelViewSet

from goods import models
from goods.api import serializers


class TradeNameViewSet(ModelViewSet):
    queryset = models.TradeName.objects.all()
    serializer_class = serializers.TradeNameSerializer
    permission_class = [DjangoObjectPermissions]


class MakerViewSet(ModelViewSet):
    queryset = models.Maker.objects.all()
    serializer_class = serializers.MakerSerializer
    permission_class = [DjangoObjectPermissions]


class PackingViewSet(ModelViewSet):
    queryset = models.Packing.objects.all()
    serializer_class = serializers.PackingSerializer
    permission_class = [DjangoObjectPermissions]


class UnitViewSet(ModelViewSet):
    queryset = models.Unit.objects.all()
    serializer_class = serializers.UnitSerializer
    permission_class = [DjangoObjectPermissions]


class OriginalPackingViewSet(ModelViewSet):
    queryset = models.OriginalPacking.objects.all()
    serializer_class = serializers.OriginalPackingSerializer
    permission_class = [DjangoObjectPermissions]


class DosagePackingViewSet(ModelViewSet):
    queryset = models.DosagePacking.objects.all()
    serializer_class = serializers.DosagePackingSerializer
    permission_class = [DjangoObjectPermissions]


class CatalogViewSet(ModelViewSet):
    queryset = models.Catalog.objects.all()
    serializer_class = serializers.CatalogSerializer
    permission_class = [DjangoObjectPermissions]


class GoodViewSet(ModelViewSet):
    queryset = models.Good.objects.all()
    serializer_class = serializers.GoodSerializer
    permission_class = [DjangoObjectPermissions]


class GoodImageViewSet(ModelViewSet):
    queryset = models.GoodImage.objects.all()
    serializer_class = serializers.GoodImageSerializer
    permission_class = [DjangoObjectPermissions]

goods/templates/goods/catalog_list.html
{% extends 'goods/base.html' %}
{% load i18n %}

{% block title %}
{{block.super}} | {% trans 'catalog' %}
{% endblock %}


{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:catalog-list' %}">{% trans 'catalog' %}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Catalog' %}
{% endblock page_title %}

{% block content %}
<div class="col-12">

  <div class="card">
    {% if perms.goods.add_catalog %}

    <div class="card-header">
      <h3 class="card-title"></h3>

      <div class="card-tools">
	<div class="card-tools">
          <a type="button" href="{% url 'goods:catalog-create' %}" class="btn btn-info btn-sm" title="{% trans 'Аdding a new entry' %}">
            <i class="fa fa-plus"></i> {% trans 'Add' %}
          </a>
        </div>
      </div>

    </div>
    {% endif %}

    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>{% trans 'Name' %}</th>
	    <th>{% trans 'Parent' %}</th>
            <th>{% trans 'Created' %}</th>
            <th>{% trans 'Updated' %}</th>
          </tr>
        </thead>
        <tbody>
	  {% for item in object_list %}
          <tr onclick="window.location.href = '{% url "goods:catalog-detail" item.slug %}'">
            <td>{{item.name}}</td>
	    <td>{{item.parent}}</td>
            <td>{{item.created}}</td>
            <td>{{item.updated}}</td>
          </tr>
	  {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->

</div>
{% endblock %}

goods/templates/goods/good_detail.html
{% extends 'goods/good_list.html' %}
{% load i18n %}

{% block title %}
{{block.super}} | {{object.name}}
{% endblock %}

{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:goods-detail' object.slug %}">{{object.name}}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Parm Product' %} {{object.name}}
{% endblock page_title %}


{% block content %}
<div class="col-12">

  <div class="card">

    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
	    <th>{% trans 'Catalog' %}</th>
            <th>{% trans 'Trade Name' %}</th>
	    <th>{% trans 'Maker' %}</th>
	    <th>{% trans 'Original Packing' %}</th>
	    <th>{% trans 'Dosage Packing' %}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{object.catalog}}</td>
	    <td>{{object.trade_name}}</td>
            <td>{{object.maker}}</td>
            <td>{{object.original_packing}}</td>
	    <td>{{object.dosage_packing}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      {% if perms.goods.delete_good %}
      <a type="button" href="{% url 'goods:goods-delete' object.slug %}" class="btn btn-default">{% trans 'Delete' %}</a>
      {% endif %}
      <a type="button" href="{% url 'goods:goods-list' %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
      {% if perms.goods.change_good %}
      <a type="button" href="{% url 'goods:goods-update' object.slug %}" class="btn btn-info float-right">{% trans 'Update' %}</a>
      {% endif %}
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->

</div>
{% endblock content %}

goods/templates/goods/good_form.html
{% extends 'goods/good_list.html' %}
{% load i18n crispy_forms_tags %}

{% block title %}
{{block.super}} | {% trans 'Create' %}
{% endblock %}


{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:goods-create' %}">{% trans 'create' %}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Pharm Product' %}
{% endblock page_title %}


{% block content %}
<div class="container-fluid col-6">

  <div class="card card-info">
    <div class="card-header">
      <h3 class="card-title">{% trans 'Form' %}</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form class="form-horizontal" method="post">
      <div class="card-body">
	{% csrf_token %}
	{{ form|crispy }}
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
	<button type="submit" class="btn btn-info">{% trans 'Send' %}</button>
	{% url 'goods:goods-create' as urlcreate %}
	{% if request.path_info == urlcreate %}
	<a type="button" href="{% url 'goods:goods-list' %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
	{% else %}
	<a type="button" href="{% url 'goods:goods-detail' object.slug %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
	{% endif %}
      </div>
      <!-- /.card-footer -->
    </form>
  </div>

</div>
{% endblock content %}

goods/templates/goods/maker_detail.html
{% extends 'goods/maker_list.html' %}
{% load i18n %}

{% block title %}
{{block.super}} | {{object.name}}
{% endblock %}

{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:maker-detail' object.slug %}">{{object.name}}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Maker' %} {{object.name}}
{% endblock page_title %}


{% block content %}
<div class="col-12">

  <div class="card">

    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Created' %}</th>
            <th>{% trans 'Updated' %}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{object.name}}</td>
            <td>{{object.created}}</td>
            <td>{{object.updated}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      {% if perms.goods.delete_maker %}
      <a type="button" href="{% url 'goods:maker-delete' object.slug %}" class="btn btn-default">{% trans 'Delete' %}</a>
      {% endif %}
      <a type="button" href="{% url 'goods:maker-list' %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
      {% if perms.goods.change_maker %}
      <a type="button" href="{% url 'goods:maker-update' object.slug %}" class="btn btn-info float-right">{% trans 'Update' %}</a>
      {% endif %}
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->

</div>
{% endblock content %}

goods/templates/goods/packing_detail.html
{% extends 'goods/packing_list.html' %}
{% load i18n %}

{% block title %}
{{block.super}} | {{object.name}}
{% endblock %}

{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:packing-detail' object.slug %}">{{object.name}}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Packing' %} {{object.name}}
{% endblock page_title %}


{% block content %}
<div class="col-12">

  <div class="card">

    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Created' %}</th>
            <th>{% trans 'Updated' %}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{object.name}}</td>
            <td>{{object.created}}</td>
            <td>{{object.updated}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      {% if perms.goods.delete_packing %}
      <a type="button" href="{% url 'goods:packing-delete' object.slug %}" class="btn btn-default">{% trans 'Delete' %}</a>
      {% endif %}
      <a type="button" href="{% url 'goods:packing-list' %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
      {% if perms.goods.change_packing %}
      <a type="button" href="{% url 'goods:packing-update' object.slug %}" class="btn btn-info float-right">{% trans 'Update' %}</a>
      {% endif %}
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->

</div>
{% endblock content %}

goods/templates/goods/tradename_detail.html
{% extends 'goods/tradename_list.html' %}
{% load i18n %}

{% block title %}
{{block.super}} | {{object.name}}
{% endblock %}

{% block crumbs %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'goods:tradename-detail' object.slug %}">{{object.name}}</a></li>
{% endblock crumbs %}

{% block page_title %}
{% trans 'Detail' %}: {{object.name}}
{% endblock page_title %}


{% block content %}
<div class="col-12">

  <div class="card">

    <!-- /.card-header -->
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap">
        <thead>
          <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Created' %}</th>
            <th>{% trans 'Updated' %}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{object.name}}</td>
            <td>{{object.created}}</td>
            <td>{{object.updated}}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      {% if perms.goods.delete_tradename %}
      <a type="button" href="{% url 'goods:tradename-delete' object.slug %}" class="btn btn-default">{% trans 'Delete' %}</a>
      {% endif %}
      <a type="button" href="{% url 'goods:tradename-list' %}" class="btn btn-default float-right">{% trans 'Cancel' %}</a>
      {% if perms.goods.change_tradename %}
      <a type="button" href="{% url 'goods:tradename-update' object.slug %}" class="btn btn-info float-right">{% trans 'Update' %}</a>
      {% endif %}
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->

</div>
{% endblock content %}